"""flight_mode_tables

Revision ID: 19a976d8f95d
Revises: fd0f2c57b8e5
Create Date: 2026-05-09 19:25:59.312224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a976d8f95d'
down_revision: Union[str, Sequence[str], None] = 'fd0f2c57b8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_index(op.f('ix_blocked_dates_id'), 'blocked_dates', ['id'], unique=False)
    op.create_table('flight_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_modes_id'), 'flight_modes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_modes_id'), table_name='flight_modes')
    op.drop_table('flight_modes')
    op.drop_index(op.f('ix_blocked_dates_id'), table_name='blocked_dates')
    op.drop_table('blocked_dates')
    # ### end Alembic commands ###
