"""create_sales_table

Revision ID: 650307772020
Revises: e48522439f1f
Create Date: 2026-05-08 19:33:02.535765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '650307772020'
down_revision: Union[str, Sequence[str], None] = 'e48522439f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registered_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['registered_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_expenses_id'), 'corporate_expenses', ['id'], unique=False)
    op.create_table('headquarters_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.Enum('PIX', 'DINHEIRO', 'CARTAO', name='paymentmethodenum'), nullable=False),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registered_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['registered_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_headquarters_sales_id'), 'headquarters_sales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_headquarters_sales_id'), table_name='headquarters_sales')
    op.drop_table('headquarters_sales')
    op.drop_index(op.f('ix_corporate_expenses_id'), table_name='corporate_expenses')
    op.drop_table('corporate_expenses')
    # ### end Alembic commands ###
