"""add_pert_jsonb_column

Revision ID: 8d0243912135
Revises: 0921fe554147
Create Date: 2026-03-27 19:21:39.939153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d0243912135'
down_revision: Union[str, Sequence[str], None] = '0921fe554147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('pert_diagnostic', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_by')
    op.drop_column('projects', 'pert_diagnostic')
    # ### end Alembic commands ###
