"""create_partners_table

Revision ID: a59a34365c60
Revises: 2819be93ce00
Create Date: 2026-05-15 07:26:58.951668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59a34365c60'
down_revision: Union[str, Sequence[str], None] = '2819be93ce00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.Column('representative', sa.String(length=100), nullable=True),
    sa.Column('expectations', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('CAPTACAO', 'ATIVACAO', 'ENCANTAMENTO', 'GERENCIAMENTO', 'CONGELADO', 'FINALIZADA', name='partnerstatusenum'), nullable=False),
    sa.Column('temperature', sa.Enum('QUENTE', 'FRIO', name='partnertemperatureenum'), nullable=False),
    sa.Column('metrificacao', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partners_id'), 'partners', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partners_id'), table_name='partners')
    op.drop_table('partners')
    # ### end Alembic commands ###
