"""Recria_tabela_messages

Revision ID: f450cf921666
Revises: 522e4d18f3f9
Create Date: 2026-06-15 17:22:24.125309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f450cf921666'
down_revision: Union[str, Sequence[str], None] = '522e4d18f3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    As tabelas `messages` e `tickets` já são criadas pela migration inicial
    (522e4d18f3f9). Esta migration foi criada para recuperar bancos em que
    essas tabelas estavam ausentes, então só cria quando ainda não existem.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'messages' not in existing_tables:
        op.create_table('messages',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    elif 'ix_messages_id' not in {idx['name'] for idx in inspector.get_indexes('messages')}:
        op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)

    if 'tickets' not in existing_tables:
        op.create_table('tickets',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.Column('assigned_to_id', sa.Integer(), nullable=True),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', name='ticketstatus'), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id', 'created_at')
        )
        op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    elif 'ix_tickets_id' not in {idx['name'] for idx in inspector.get_indexes('tickets')}:
        op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
