"""create_absence_requests_table

Revision ID: fd0f2c57b8e5
Revises: 9ae5c636ede5
Create Date: 2026-05-09 18:16:58.219878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd0f2c57b8e5'
down_revision: Union[str, Sequence[str], None] = '9ae5c636ede5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('absence_requests', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'DENIED', 'HOMEOFFICE', name='absencestatusenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('absence_requests', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'DENIED', 'HOMEOFFICE', name='absencestatusenum'),
               nullable=True)
    # ### end Alembic commands ###
